### ISSUE TITLE
CAD File? 

### ISSUE THREAD

**Issue by notDave0** [openKolibri/halo-90#8]
Thanks for this project. These are amazing! I'd like to model up and print some clear cases for mine. Do you have a solid model for the populated PCBAs?

**Comment by sawaiz** [comment]
Sure, see if this works for you. You can also export directly form KiCad, and I might have IPT files if those would be better, I’m traveling today, so don’t have access to them just yet.

Regards,
Sawaiz

**Comment by notDave0** [comment]
An .ipt would work well for me. I don't currently run KiCad

Regards,
Dave

**Comment by sawaiz** [comment]
Sorry I completely forgot about this. Here is a step and ipt file. 

[halo-90.zip](https://github.com/openKolibri/halo-90/files/13942997/halo-90.zip)
